spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dormitory?useSSL=true
    username: root
    password: root
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
  thymeleaf:
    cache: false


imageFilePath: C://Users/王博越/IdeaProjects/dormitory/src/main/webapp/static/images




alipayconfig:
  appid: 2016092600603102
  rsa_private_key: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCM+HsfUiNnhtoDjgj3cdhke5xLvFvAPJ2tJFdnmXS8EKRRxODvzyIWJ831AhJeXBIlAk0tzyrKKtRzlnRyWmoH3E7X7nupS/Apx2MfkOsn8pMsoGmdepkRw/9ric3JtbiKDZ7u1/y+UNvFcFXrbaH+a/0uGmx1M5hG9lqLKia97BiYOPmUMscPlLHmymYtnVJTZ85S7VhXB0CZ3Wbo7WUfwCQHV29GdK3JuV3YRpfhE5sKrx6WYpOj8U/I0fdcZZMuuxjMqdZXqXlZ+h6EVxLAbLLS1ovt8oBUDWE3J0swP/ZyBZg+AniSzY24ez4EpSkHTWVWNq2z/lsuKqd/2bnlAgMBAAECggEAONckBd//qImmNFK76NH9l56DycHcGOoYBa0mlP46JG5tYw8IR4l0TAymrci1EVj8c/G2nubucO/OFAExWL5+DEdXfxeIwx18a8waeqrbNpNHpnHTxAyf1Zr6zSiWUmO0Ue3mDJYIMdC2nKiL7E6bR9PRFRrQan1wRASnQ3+ueVszifUfpz6/zTAQ26IZWRCJO5+IH9S3+JTC45RKTKV6HPHFglIiVpW2uCrFynKHnude2buuR/dJnIZserueaItAf7v12vH1pjja9GuTC4Qu4LZ+Dvxkzg4nH3OgRF8ozMWx5Uc4i0CEgVJ/NNzXEMGosTWeI3U6ZGd9cDUzpS1jzQKBgQDZJsnoCDMhDanFIpbvI1jDID0FeZy/Ac7WcWWf6hDlHg/1/HsiDmrgMWm5K9YgRbu8bccRrzCK9LzoNfTp7oBzeuFs12AuafznLhh9/TUNsQwuWlDflZyaWdElwGNuFgY+YAQtXFBZvXTuZbrUPE8FhZ0u1XWUZYyDwpgj4AFgBwKBgQCmMLj/+DoORKYD3+2MYXgCJN7GzR6StpXW15epOb70X0/q4r8xb+DUmbONzG9ctZPvsQXZlKFrKaODjO8AqMBtEcTdxhI58Oyf/kQeTbsBcBYx5aaapB+iobriMN+KQMmsVrNYZIneuJo7kIVCnmQYLs5ljktV4MooLjuRT0CDswKBgA3dBBbkLx91F9mWE7zArPIIJN0snm0zWFkodCx5bQqzmKFDtTi/YuNdRDqmKc11pj6pY4Qlgxvb9BN/Hluw9lJpDes89M8BxTudHcMtXy24l+Z9rZwYmR7hjRCz76UfktZ4msuqkRapmcV+iSbzkrfvh9Ftn0wSD5551ey0aGIRAoGAcIMR7HHQVDKTtpHW0DB4v/LYQ/1AkpE8dlw1WCM5LVaN03a5fC3DKAv67KgYSMrBogfV7w1aDyP8iKZUdLzKsczS3FYppsJ+YH8S/PUhAwMwc42HsrAknsUhsdrmrEHah2uXNeOzF28hM+xO2+BB4cFmiIjCZhyuoG9UcrcV9VMCgYEAlm+azKBc/IbS1jwvZrOZfETAhwPeKmUcpJabgIje03cnoi/N701tCUpsDmOTL88sZr8KZJBTrma5emW+rOKUMiGMvo8hWZFmsg5sz3742TrbCYG2srVRQG66hNSv7dbEf0f/FaczdU28g/QJpg5rX+Yo0mDpoGLkDlA/t+O18Vg=
  notify_url: http://localhost:8080/alipay/notifyUrl
  return_url: http://localhost:8080/alipay/returnUrl
  url: https://openapi.alipaydev.com/gateway.do
  charset: UTF-8
  format: json
  alipay_public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAjPh7H1IjZ4baA44I93HYZHucS7xbwDydrSRXZ5l0vBCkUcTg788iFifN9QISXlwSJQJNLc8qyirUc5Z0clpqB9xO1+57qUvwKcdjH5DrJ/KTLKBpnXqZEcP/a4nNybW4ig2e7tf8vlDbxXBV622h/mv9LhpsdTOYRvZaiyomvewYmDj5lDLHD5Sx5spmLZ1SU2fOUu1YVwdAmd1m6O1lH8AkB1dvRnStybld2EaX4RObCq8elmKTo/FPyNH3XGWTLrsYzKnWV6l5WfoehFcSwGyy0taL7fKAVA1hNydLMD/2cgWYPgJ4ks2NuHs+BKUpB01lVjats/5bLiqnf9m55QIDAQAB
  signtype: RSA2
